<!DOCTYPE script PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>PhpTaskDaemon Status</title>
<?php if ((isset($this->status['pid'])) && ($this->status['pid']>0)): ?>
	<script type="text/JavaScript">
	<!--
	setTimeout("location.href = '/status/';",500);
	//   -->
	</script>
<?php endif;?>
</head>
<body>
<?php if ((isset($this->status['pid'])) && ($this->status['pid']>0)): ?>
	<p>
		PhpTaskDaemon is running
		<b><?php echo $this->escape(count($this->status['childs'])) ?></b> tasks 
		(main pid: <b><?php echo $this->escape($this->status['pid']) ?></b>).
	</p>
	
	<?php if ($this->gearmanclient): ?>
		<p>
			<b>Example3 Gearman task inserted!</b>
		</p>
	<?php endif;?>
	
	<table>
	<tr>
		<td width="75"><b>PID</b></td>
		<td width="75"><b>Memory</b></td>
		<td width="200"><b>Task</b></td>
		<td width="250"><b>Progress</b></td>
		<td width="400"><b>Description</b></td>
	</tr>
	<?php foreach ($this->status['childs'] as $childPid): ?>
	<tr>
		<td colspan="5">&nbsp;</td>
	</tr>
	<tr bgcolor="eeeeee">
		<td><?php echo $this->escape($this->status['manager-' . $childPid]['childPid']) ?></td>
		<td><?php echo $this->escape(ucfirst($this->status['manager-' . $childPid]['type'])) ?></td>
		<td>Manager (<?php echo $this->escape(ucfirst(str_replace('SiteSpeed\\Daemon\\Task\\', '', $this->status['manager-' . $childPid]['name']))) ?>)</td>
		<td>
			<?php
				$queueProgress = round((($this->status['manager-' . $childPid]['loaded']-$this->status['manager-' . $childPid]['count']) / $this->status['manager-' . $childPid]['loaded'])*100); 
			?>
			<img src="/images/progress1.gif" height="15" width="<?php echo $this->escape($queueProgress*2) ?>" />
			<?php echo $this->escape($queueProgress) ?>%
		</td>
		<td>
			Queued: <?php echo $this->escape($this->status['manager-' . $childPid]['count']) ?> / <?php echo $this->escape($this->status['manager-' . $childPid]['loaded']) ?>
			Done: <?php echo $this->escape($this->status['manager-' . $childPid]['done']) ?>
		</td>
	</tr>
	<tr>
		<td><?php echo $this->escape($this->status['manager-' . $childPid]['childPid']) ?></td>
		<td><?php echo $this->escape($this->status['manager-' . $childPid]['task-' . $childPid . '-memory']) ?></td>
		<td>Task</td>
		<?php if (isset($this->status['manager-' . $childPid]['task-' . $childPid . '-message'])): ?>
			<td>
				<img src="/images/progress2.gif" height="15" width="<?php echo $this->escape($this->status['manager-' . $childPid]['task-' . $childPid . '-progress']*2) ?>" />
				<?php echo $this->escape($this->status['manager-' . $childPid]['task-' . $childPid . '-progress']) ?>%
			</td>
			<td><?php echo $this->escape($this->status['manager-' . $childPid]['task-' . $childPid . '-message']) ?></td>
		<?php else :?>
			<td></td>
			<td></td>
		<?php endif; ?>
	</tr>
	<?php endforeach; ?>
	</table>

	
<?php else: ?>
    <p>PhpTaskDaemon is <b>not</b> running.</p>
<?php endif;?>

<form action="/status/" method="post">
<input type="submit" name="example3-gearman" value="Insert Example3 Job" />
</form>

</body>
</html>